USE [master]
GO
/****** Object:  Database [People]    Script Date: 07/01/2025 19:32:05 ******/
CREATE DATABASE [People]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'People', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\People.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'People_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\People_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [People] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [People].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [People] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [People] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [People] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [People] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [People] SET ARITHABORT OFF 
GO
ALTER DATABASE [People] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [People] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [People] SET AUTO_UPDATE_STATISTICS OFF 
GO
ALTER DATABASE [People] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [People] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [People] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [People] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [People] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [People] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [People] SET  DISABLE_BROKER 
GO
ALTER DATABASE [People] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [People] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [People] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [People] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [People] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [People] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [People] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [People] SET RECOVERY FULL 
GO
ALTER DATABASE [People] SET  MULTI_USER 
GO
ALTER DATABASE [People] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [People] SET DB_CHAINING OFF 
GO
ALTER DATABASE [People] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [People] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [People] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [People] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'People', N'ON'
GO
ALTER DATABASE [People] SET QUERY_STORE = ON
GO
ALTER DATABASE [People] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [People]
GO
/****** Object:  Table [dbo].[Authors]    Script Date: 07/01/2025 19:32:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Authors](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[DateOfBirth] [datetime] NULL,
 CONSTRAINT [PK_Author] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[Authors] ([Id], [Name], [DateOfBirth]) VALUES (N'183918e0-9ab3-4308-9ea1-06033293b991', N'Philip Pullman', CAST(N'1946-10-19T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[Authors] ([Id], [Name], [DateOfBirth]) VALUES (N'd0dd74d2-56d6-4def-a12c-3f4b662ce43e', N'Hilary Mantel', CAST(N'1952-07-06T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[Authors] ([Id], [Name], [DateOfBirth]) VALUES (N'755a2cfe-58e0-4f18-941f-7f8564e1be42', N'Robert Macfarlane', CAST(N'1976-08-15T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[Authors] ([Id], [Name], [DateOfBirth]) VALUES (N'89d16873-4fa9-4ddf-a815-cf7c470bff8b', N'Andrea Levy', CAST(N'1956-03-07T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[Authors] ([Id], [Name], [DateOfBirth]) VALUES (N'b928594d-ff5c-453e-bd93-d216b33fc3bd', N'Cormac McCarthy', CAST(N'1933-07-20T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[Authors] ([Id], [Name], [DateOfBirth]) VALUES (N'eaab7f0f-21af-4d26-8af8-ddd6eb1506cc', N'Chimamanda Ngozi Adichie', CAST(N'1977-09-15T00:00:00.000' AS DateTime))
GO
/****** Object:  StoredProcedure [dbo].[GetAuthors]    Script Date: 07/01/2025 19:32:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GetAuthorById]
(
    @pAuthorId  UNIQUEIDENTIFIER
) 
AS 
BEGIN
    SELECT Id, Name, DateOfBirth FROM Authors where Id = @pAuthorId 
END
GO
USE [master]
GO
ALTER DATABASE [People] SET  READ_WRITE 
GO
